baseurl          = "/"
title           = "Candidate"
languageCode    = "en-uk"
paginate        = "10"                                                                 # Number of posts per page
#theme           = "mainroad"
disqusShortname = ""                                                            # Enable comments by entering your Disqus shortname
googleAnalytics = ""                                                            # Enable Google Analytics by entering your tracking id

[Author]
    name = M. Daniels
    bio = Experienced Risk Manager and quant. Track record of helping clients ientify root cause issues and invest appropriatly to address regulatory and business priorities.
    avatar = "img/avatar.png"


[Params]
    gs_id           = "ab34c8"
    subtitle        = "Photobox Group Security - Candidate Site"                # Subtitle of your site
    description     = Limited candidtae responce to obtain an interview             # Description of your site
    opengraph       = true
    readmore        = true                                                      # Show "Read more" button in list if true
    leftsidebar     = false                                                     # Move sidebar to the left side if true
    authorbox       = true
    post_navigation = true
    postSections    = ["post"]


[Params.widgets]
    search          = false
    recent_articles = true                              # Enable "Recent arcticles" widget
    categories      = false                             # Enable "Categories" widget
    tags            = false                             # Enable "Tags" widget
    tags_counter    = false                             # Enable counter for each tag in "Tags" widget (disabled by default)
